include:
  - docker-compose.yml

services:
  finality-gadget:
    container_name: finality-gadget
    # https://github.com/babylonlabs-io/finality-gadget/commit/37a8b1c9b2698c9967bbc060583668d6c7a1e6f9
    image: babylonlabs/finality-gadget:37a8b1c9b2698c9967bbc060583668d6c7a1e6f9
    command: >
      opfgd start --cfg /home/finality-gadget/opfgd.toml
    ports:
      - "50051:50051"
      - "18080:8080"
    networks:
      localnet:
        ipv4_address: 192.168.10.16
    volumes:
      - ../.testnets/finality-gadget:/home/finality-gadget
    depends_on:
      - babylondnode0
      - bitcoindsim
    restart: unless-stopped
