include:
  - docker-compose.yml

services:
  finality-gadget:
    container_name: finality-gadget
    # TODO: replace with babylonlabs/finality-gadget once image published
    image: parketh/finality-gadget:8d38bf769d2054dc647f96ea5f55d4dd68b8a72a
    command: >
      opfgd start --cfg /home/finality-gadget/opfgd.toml
    ports:
      - "50051:50051"
      - "18080:8080"
    networks:
      localnet:
        ipv4_address: 192.168.10.16
    volumes:
      - ../.testnets/finality-gadget:/home/finality-gadget
    depends_on:
      - babylondnode0
      - bitcoindsim
    restart: unless-stopped
